server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: user_web
  registry:
    address: zookeeper://192.168.135.233:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3
  protocol:
    port: -1